In [0]:
#comma가 없다는것은 리스트가 아니다.
import numpy as np
ls = [2,6,8,7,5,6]
x =  np.array([2,6,8,7,5,6])
print(ls[2],ls[:4],ls[1:4:2])
print(x[2], x[:4], x[1:4:2])

ls[2:5] = [6] #2번부터 5번전까지의 리스트를 [6]으로 변경
print(ls) #mutable data
#x[2:5] =6
print(x)

8 [2, 6, 8, 7] [6, 7]
8 [2 6 8 7] [6 7]
[2, 6, 6, 6]
[2 6 8 7 5 6]


In [0]:
x_sub1 = x[1:5]
x_sub2 = x[1:5].copy()

print(x, x_sub1, x_sub2)

x[2] = 100

print(x, x_sub1, x_sub2)



[2 6 8 7 5 6] [6 8 7 5] [6 8 7 5]
[  2   6 100   7   5   6] [  6 100   7   5] [6 8 7 5]


In [32]:
A = np.array([  [2,6,8,7], [25,31,78,96], [101,204,109,157]  ])
print(A)
print("\n")
print(A[2],"\n","\n", A[:2])
print("\n")
print(A[2][1], A[2,1])
print("\n")
print(A[:2, 1:3])

[[  2   6   8   7]
 [ 25  31  78  96]
 [101 204 109 157]]


[101 204 109 157] 
 
 [[ 2  6  8  7]
 [25 31 78 96]]


204 204


[[ 6  8]
 [31 78]]


In [46]:
arr3d = np.array([[[2,6,8,7], [25,31,78,96]],
                  [[102,297,304,487], [3,5,9,5]]])
print(arr3d)
print("\n")
print(arr3d[0][1][2],arr3d[0,1,2])
print("\n")
print(arr3d[0,1])

arr3d_sub1 = arr3d[0,1]
arr3d_sub2 = arr3d[0,1].copy()
print(arr3d_sub1,arr3d_sub2)
#arr3d_sub1[0,1,2] =  100
#print(arr3d_sub1,arr3d_sub2)


[[[  2   6   8   7]
  [ 25  31  78  96]]

 [[102 297 304 487]
  [  3   5   9   5]]]


78 78


[25 31 78 96]
[25 31 78 96] [25 31 78 96]


In [58]:
name = np.array(["남자", "여자", "남자", "남자", "남자", "여자"])
score = np.array([[10,20,30,40],[8,15,24,31],[5,11,20,25],
                [6,9,16,17],[10,17,21,27],[9,13,27,31]])
name_bool = name =="여자"

print(name,"\n","\n",score,"\n","\n",name_bool)

['남자' '여자' '남자' '남자' '남자' '여자'] 
 
 [[10 20 30 40]
 [ 8 15 24 31]
 [ 5 11 20 25]
 [ 6  9 16 17]
 [10 17 21 27]
 [ 9 13 27 31]] 
 
 [False  True False False False  True]


In [61]:
female = score[name_bool]
print(female)

print("\n")

male = score[~name_bool]
print(male)

[[ 8 15 24 31]
 [ 9 13 27 31]]


[[10 20 30 40]
 [ 5 11 20 25]
 [ 6  9 16 17]
 [10 17 21 27]]


In [73]:
cls = np.array(["1학년", "2학년","3학년","1학년", "2학년","3학년"])

score = np.array([[10,20,30,40],[8,15,24,31],[5,11,20,25],
                  [6,7,16,17],[10,17,21,27],[9,13,27,31]])

print(score[(cls=="1학년") | (cls == "2학년")])

[[10 20 30 40]
 [ 8 15 24 31]
 [ 6  7 16 17]
 [10 17 21 27]]


In [74]:
score[(cls=="1학년") | (cls == "2학년")] = 0
print(score)

[[ 0  0  0  0]
 [ 0  0  0  0]
 [ 5 11 20 25]
 [ 0  0  0  0]
 [ 0  0  0  0]
 [ 9 13 27 31]]


In [75]:
score[score >= 20] =100
print(score)

[[  0   0   0   0]
 [  0   0   0   0]
 [  5  11 100 100]
 [  0   0   0   0]
 [  0   0   0   0]
 [  9  13 100 100]]


In [80]:
arr = np.random.rand(7,4)
print(arr)

[[0.49328911 0.74625439 0.67486681 0.74266397]
 [0.04774902 0.77923024 0.66329729 0.66106296]
 [0.90797861 0.64235168 0.61224446 0.13496036]
 [0.16177257 0.5525705  0.59531411 0.9720748 ]
 [0.62750262 0.46313194 0.64182839 0.71749467]
 [0.10036059 0.96901286 0.71384014 0.07765201]
 [0.4957734  0.10159982 0.10943886 0.95906143]]


In [82]:
arr1 = arr[[6,3,5]] #6번행 3번행 5번행 차례대로 가져와라 이게 펜스 인덱싱
print(arr1)

[[0.4957734  0.10159982 0.10943886 0.95906143]
 [0.16177257 0.5525705  0.59531411 0.9720748 ]
 [0.10036059 0.96901286 0.71384014 0.07765201]]


In [83]:
arr2 = arr[[-1,-4,-2]] #맨 마지막 행 부터 0, -1, -2 순서
print(arr2)

[[0.4957734  0.10159982 0.10943886 0.95906143]
 [0.16177257 0.5525705  0.59531411 0.9720748 ]
 [0.10036059 0.96901286 0.71384014 0.07765201]]


In [84]:
arr3 = arr[[5,0,2],[1,0,2]] #5번,0번,2번행에서 (5번행에서 가로로 1번째 값, 0번행에서 가로로 0번째 값을 가져온다.
print(arr3)

[0.96901286 0.49328911 0.61224446]


In [88]:
arr4 = arr[[5,0,2]][:,[1,0,2]] #5,0,2행에서 1번원소,0번원소,2번원소를 차례대로 뽑아옴
arr5 = arr[np.ix_([5,0,2],[1,0,2])]

print(arr4)
print(arr5)

[[0.96901286 0.10036059 0.71384014]
 [0.74625439 0.49328911 0.67486681]
 [0.64235168 0.90797861 0.61224446]]
[[0.96901286 0.10036059 0.71384014]
 [0.74625439 0.49328911 0.67486681]
 [0.64235168 0.90797861 0.61224446]]


In [96]:
arr = np.arange(28).reshape(4,7)
print(arr)
print("\n")
arr1 = arr.T
arr2 = arr.transpose()
print(arr1)
print("\n")
print(arr2)

[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]]


[[ 0  7 14 21]
 [ 1  8 15 22]
 [ 2  9 16 23]
 [ 3 10 17 24]
 [ 4 11 18 25]
 [ 5 12 19 26]
 [ 6 13 20 27]]


[[ 0  7 14 21]
 [ 1  8 15 22]
 [ 2  9 16 23]
 [ 3 10 17 24]
 [ 4 11 18 25]
 [ 5 12 19 26]
 [ 6 13 20 27]]


In [101]:
arr = np.arange(24).reshape(2,4,3) #앞에서부터 인덱스가 0,1,2임
print(arr)
print("\n")
arr1 = arr.transpose(2,0,1) #위의 인덱스를 이용 인덱스 번호에 따라서 3,2,4가 들어감
print(arr1)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]


[[[ 0  3  6  9]
  [12 15 18 21]]

 [[ 1  4  7 10]
  [13 16 19 22]]

 [[ 2  5  8 11]
  [14 17 20 23]]]


NaN == null

In [121]:
x = np.array([2.5, 5.6, 8.1, 3.9, 5.7])
y = np.array([2, 6, -3, 4, -5])
A = np.array([x,y])

print(np.sqrt(x))
print("\n")
print(np.exp(x))
print("\n")
print(np.rint(np.exp(x))) #소수점 자르기
print("\n")
print(np.log(x))
print("\n")
print(np.abs(y))
print("\n")
print(np.sign(y))
print("\n")
r, q = np.modf(A) #실수부봐 소수부로 찢음
print(r)
print("\n")
print(q)

[1.58113883 2.36643191 2.84604989 1.97484177 2.38746728]


[  12.18249396  270.42640743 3294.46807528   49.40244911  298.86740097]


[  12.  270. 3294.   49.  299.]


[0.91629073 1.7227666  2.09186406 1.36097655 1.74046617]


[2 6 3 4 5]


[ 1  1 -1  1 -1]


[[ 0.5  0.6  0.1  0.9  0.7]
 [ 0.   0.  -0.   0.  -0. ]]


[[ 2.  5.  8.  3.  5.]
 [ 2.  6. -3.  4. -5.]]


In [140]:
A = (np.random.randn(12)*3+10).reshape(4,3)
B = np.arange(1,13).reshape(4,3)

print(A+B)
print("\n")
print(np.add(A,B))
print("\n")
print(np.subtract(A,B))
print("\n")
print(np.multiply(A,B))
print(np.divide(A,B))
print(np.floor_divide(A,B))

[[ 8.32988844  6.83341382 12.29920332]
 [16.5646985  18.38763865 17.96870066]
 [11.1691189  13.58126066 19.75628904]
 [21.58076365 20.33021912 22.64453224]]


[[ 8.32988844  6.83341382 12.29920332]
 [16.5646985  18.38763865 17.96870066]
 [11.1691189  13.58126066 19.75628904]
 [21.58076365 20.33021912 22.64453224]]


[[ 6.32988844  2.83341382  6.29920332]
 [ 8.5646985   8.38763865  5.96870066]
 [-2.8308811  -2.41873934  1.75628904]
 [ 1.58076365 -1.66978088 -1.35546776]]


[[  7.32988844   9.66682764  27.89760995]
 [ 50.258794    66.93819326  71.81220393]
 [ 29.18383227  44.65008529  96.80660133]
 [115.80763653 102.63241033 127.73438685]]
[[7.32988844 2.41670691 3.09973444]
 [3.14117462 2.67752773 1.99478344]
 [0.59558841 0.69765758 1.19514323]
 [1.15807637 0.84820174 0.88704435]]
[[7. 2. 3.]
 [3. 2. 1.]
 [0. 0. 1.]
 [1. 0. 0.]]


In [0]:
arr1 = (np.random.randn(12)*30 +70).reshape(4,3)
arr2 = (np.random.randn(12)*5 +10).reshape(4,3)

In [148]:
result = np.where(arr>=60, arr2,-1)
print(result)

[[[-1. -1. -1.]
  [-1. -1. -1.]
  [-1. -1. -1.]
  [-1. -1. -1.]]

 [[-1. -1. -1.]
  [-1. -1. -1.]
  [-1. -1. -1.]
  [-1. -1. -1.]]]


In [155]:
arr1 = (np.random.randn(12)*5+10).reshape(4,3)
result =  np.where(arr1>=10, arr1, np.where(arr2>=10, arr2, 0))
print(result)

[[15.842382   19.96436538 13.5092616 ]
 [10.32188412 16.15629369  0.        ]
 [15.07134266 16.85190742  0.        ]
 [13.66713183 16.9878739  13.05549938]]


In [163]:
xarr = np.array([2.5, 5.6, 8.1, 3.9, 5.7]) 
print("x.sum() = {0}\tsum(x) = {1}".format(xarr.sum(), np.sum(xarr)))
print("x.mean() = {0}\tmean(x) = {1}".format(xarr.mean(), np.mean(xarr)))
print("x.std() = {0}\tstd(x) = {1}".format(xarr.std(), np.std(xarr)))

print("x.cumsum() = {0}\tcumsum(x) = {1}".format(xarr.cumsum(), np.cumsum(xarr))) #accumulated sum 누적합

x.sum() = 25.799999999999997	sum(x) = 25.799999999999997
x.mean() = 5.159999999999999	mean(x) = 5.159999999999999
x.std() = 1.8863721796082553	std(x) = 1.8863721796082553
x.cumsum() = [ 2.5  8.1 16.2 20.1 25.8]	cumsum(x) = [ 2.5  8.1 16.2 20.1 25.8]


In [184]:
xarr = np.array([[2.5, 5.6, 8.1], [3.9, 5.7, 2.9], [6.1, 9.7, 5.4],[1.4, 8.3, 4.2]])
print(xarr)
print("\n")
print("세로 평균\n{0}\n가로평균\n{1}".format(xarr.mean(axis=0),xarr.mean(axis=1)))
print("\n")
print("전체 최소값의 인덱스 : {0}".format(xarr.argmin()))
print("세로(열) 최소값의 인덱스 : {0}".format(xarr.argmin(axis=0)))
print("가로(행) 최소값의 인덱스 : {0}".format(xarr.argmin(axis=1)))
print("\n")
print("전체 누적합 : {0}".format(xarr.cumsum()))
print("열 누적합 : \n{0}".format(xarr.cumsum(axis=0)))
print("행 누적합 : \n{0}".format(xarr.cumsum(axis=1)))

[[2.5 5.6 8.1]
 [3.9 5.7 2.9]
 [6.1 9.7 5.4]
 [1.4 8.3 4.2]]


세로 평균
[3.475 7.325 5.15 ]
가로평균
[5.4        4.16666667 7.06666667 4.63333333]


전체 최소값의 인덱스 : 9
세로(열) 최소값의 인덱스 : [3 0 1]
가로(행) 최소값의 인덱스 : [0 2 2 0]


전체 누적합 : [ 2.5  8.1 16.2 20.1 25.8 28.7 34.8 44.5 49.9 51.3 59.6 63.8]
열 누적합 : 
[[ 2.5  5.6  8.1]
 [ 6.4 11.3 11. ]
 [12.5 21.  16.4]
 [13.9 29.3 20.6]]
행 누적합 : 
[[ 2.5  8.1 16.2]
 [ 3.9  9.6 12.5]
 [ 6.1 15.8 21.2]
 [ 1.4  9.7 13.9]]


In [0]:
arr = (np.random.randn(12)*5+10).reshape(4,3)

In [195]:
print(arr)
print("\n")
print((arr>=10))
print((arr>=10).sum())
print((arr>=10).mean()) #전체12개에서 true의 비율
print((arr>=10).all())  #앞의 조건에 대해서 전부 true이냐 그러면 true
print((arr>=10).any())  #하나라도 ture가 있으면 true

[[ 6.07935263 13.72872666 15.71477546]
 [12.42621024  7.07979651 12.18941922]
 [ 3.03208196  3.80497211  9.38399236]
 [ 7.8720032  16.39985338 11.16009375]]


[[False  True  True]
 [ True False  True]
 [False False False]
 [False  True  True]]
6
0.5
False
True


In [198]:
x = np.array([2.5, -5.6, -8.1])
A = np.array([[2.5, -5.6, -8.1], [-3.9, 5.7, -2.9], [-6.1, 9.7,5.4],[1.4, -8.3, 4.2]])
print("x\n{0}\nA\n{1}".format(x,A))

x
[ 2.5 -5.6 -8.1]
A
[[ 2.5 -5.6 -8.1]
 [-3.9  5.7 -2.9]
 [-6.1  9.7  5.4]
 [ 1.4 -8.3  4.2]]


In [200]:
sorted_x = x.sort()
sorted_A = A.sort()
print("x\n{0}\nA\n{1}".format(x,A))
A.sort(axis=0) #이미 정렬된것에 대해서 열에 대해 정렬
print(A)

x
[-8.1 -5.6  2.5]
A
[[-8.1 -5.6  2.5]
 [-3.9 -2.9  5.7]
 [-6.1  5.4  9.7]
 [-8.3  1.4  4.2]]
[[-8.3 -5.6  2.5]
 [-8.1 -2.9  4.2]
 [-6.1  1.4  5.7]
 [-3.9  5.4  9.7]]


In [207]:
x = np.array([1, 2, 5,6,7,9,2,4])
y = np.array([8,2,6,7])

print(" x : {0}\t y : {1}".format(x,y))
print("unique(x) : {0}".format(np.unique(x)))
print("x∪y : {0}".format(np.union1d(x,y)))

 x : [1 2 5 6 7 9 2 4]	 y : [8 2 6 7]
unique(x) : [1 2 4 5 6 7 9]
x∪y : [1 2 4 5 6 7 8 9]


In [213]:
A = np.array([[1,3,5,7],[5,3,4,7]])
B = np.array([[1,3],[5,7],[5,3],[4,7]])
C = np.array([[4,9,1,3],[7,5,2,7],[5,3,4,3],[1,4,7,9]])

print(A)
print(B)
print(C)

[[1 3 5 7]
 [5 3 4 7]]
[[1 3]
 [5 7]
 [5 3]
 [4 7]]
[[4 9 1 3]
 [7 5 2 7]
 [5 3 4 3]
 [1 4 7 9]]


In [220]:
print("AB\n{0}".format(np.dot(A,B)))
print("C행렬의 대각원소 : {0}".format(np.diag(C)))
print("\n")
print("A행렬의 1행렬을 대각원소로 하는 행렬 \n: {0}".format(np.diag(A[1])))
print("C행렬의 대각원소의 합 \n: {0}".format(np.trace(C)))
print("C행렬의 행렬식 \n{0}".format(np.linalg.det(C)))

AB
[[69 88]
 [68 97]]
C행렬의 대각원소 : [4 5 4 9]


A행렬의 1행렬을 대각원소로 하는 행렬 
: [[5 0 0 0]
 [0 3 0 0]
 [0 0 4 0]
 [0 0 0 7]]
C행렬의 대각원소의 합 
: 22
C행렬의 행렬식 
-1549.999999999999


In [221]:
print("C행렬의 행렬식 \n{0}".format(np.linalg.inv(C)))

C행렬의 행렬식 
[[-0.0516129   0.08709677  0.13870968 -0.09677419]
 [ 0.15354839 -0.0716129  -0.02516129  0.01290323]
 [-0.00903226 -0.17225806  0.23677419  0.05806452]
 [-0.05548387  0.15612903 -0.1883871   0.07096774]]


In [222]:
eig_v,eig_vec = np.linalg.eig(C)
print("eigenvalue \n{0}\neigenvector\n{0}".format(eig_v,eig_vec))

eigenvalue 
[18.95137965+0.j         -4.18786225+0.j          3.6182413 +2.53735307j
  3.6182413 -2.53735307j]
eigenvector
[18.95137965+0.j         -4.18786225+0.j          3.6182413 +2.53735307j
  3.6182413 -2.53735307j]


In [227]:
y = np.array([2, 4, 6, 3, 7, 1])
x = np.array([[1,2,3,7], [1,5,7,6], [1,6,7,3]
            ,[1,7,3,4], [1,8,4,3], [1,3,2,5]])

print("x\n{0}\ny\n{0}".format(x,y))
print(np.linalg.lstsq(x,y))

x
[[1 2 3 7]
 [1 5 7 6]
 [1 6 7 3]
 [1 7 3 4]
 [1 8 4 3]
 [1 3 2 5]]
y
[[1 2 3 7]
 [1 5 7 6]
 [1 6 7 3]
 [1 7 3 4]
 [1 8 4 3]
 [1 3 2 5]]
(array([ 1.1991453 ,  0.44871795,  0.45854701, -0.35811966]), array([5.52948718]), 4, array([20.5718539 ,  5.90695272,  3.85261955,  0.25309904]))


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:6: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  


In [233]:
np.random.seed(1)
norm_sample1 = np.random.randn(20)
print(norm_sample1)
norm_sample2 = np.random.normal(size=20)
print(norm_sample2)
norm_sample3 = np.random.normal(loc = 10,scale = 2, size=(5,4)) #10(loc)이 중간값, scale 퍼짐, size 출력크기
print(norm_sample3)

[ 1.62434536 -0.61175641 -0.52817175 -1.07296862  0.86540763 -2.3015387
  1.74481176 -0.7612069   0.3190391  -0.24937038  1.46210794 -2.06014071
 -0.3224172  -0.38405435  1.13376944 -1.09989127 -0.17242821 -0.87785842
  0.04221375  0.58281521]
[-1.10061918  1.14472371  0.90159072  0.50249434  0.90085595 -0.68372786
 -0.12289023 -0.93576943 -0.26788808  0.53035547 -0.69166075 -0.39675353
 -0.6871727  -0.84520564 -0.67124613 -0.0126646  -1.11731035  0.2344157
  1.65980218  0.74204416]
[[ 9.6163289   8.22474207  8.50568341 13.3849092 ]
 [10.10161551  8.72600871 10.38183097 14.20051027]
 [10.2403179  11.23440622 10.60034064  9.29550031]
 [ 7.7149636   9.30131456  9.58221153 11.17324638]
 [11.67796683 11.86220416 10.57117465 11.77028233]]


In [235]:
from pandas import Series, DataFrame
import pandas as pd
import numpy as np

obj = Series([14,-27,35,73])
print("Series\n{0}\nnvalues\n{1}\nindex\n{2}".format(obj, obj.values, obj.index))

Series
0    14
1   -27
2    35
3    73
dtype: int64
nvalues
[ 14 -27  35  73]
index
RangeIndex(start=0, stop=4, step=1)


In [236]:
obj = Series([14,-27,35,73],index = ["Kim","Lee","Bae","Cho"])
print("Series\n{0}\nnvalues\n{1}\nindex\n{2}".format(obj, obj.values, obj.index))

Series
Kim    14
Lee   -27
Bae    35
Cho    73
dtype: int64
nvalues
[ 14 -27  35  73]
index
Index(['Kim', 'Lee', 'Bae', 'Cho'], dtype='object')


In [238]:
obj["Lee"] = 59
print("Series[Lee,Cho]\n{0}".format(obj[["Lee","Cho"]]))

Series[Lee,Cho]
Lee    59
Cho    73
dtype: int64


In [245]:
obj = Series([96, 78, 83, 97, 68, 82], index = ["김", "이", "배", "조", "장", "강"])
print("obj\n{0}\n".format(obj))
obj1 = obj[(obj>=60)&(obj<80)] + 10
print("obj1\n{0}\n\nwxp(obj1)\n{1}".format(obj1, np.exp(obj1)))

obj
김    96
이    78
배    83
조    97
장    68
강    82
dtype: int64

obj1
이    88
장    78
dtype: int64

wxp(obj1)
이    1.651636e+38
장    7.498417e+33
dtype: float64


In [248]:
dic ={"stat" : 270, "econ" : 150, "math" : 210, "comp" : 175}
obj = Series(dic)
print(dic)
obj2 = Series(dic, index = ["econ", "stat", "engi", "math"])
print(obj2)

{'stat': 270, 'econ': 150, 'math': 210, 'comp': 175}
econ    150.0
stat    270.0
engi      NaN
math    210.0
dtype: float64


In [254]:
#print("obj\n{0}\n")
obj1 = Series([95,75,85,95], index = ["Kim", "Lee", "Bae", "Cho"])
obj2 = Series([65,81,73,60,71], index =["Lee", "Bae", "jang", "Cho", "kang" ])
obj_sum = obj1 +obj2
obj_sum.name = "Total score" #Series의 이름
obj_sum.index.name = "choi"
print(obj_sum)

choi
Bae     166.0
Cho     155.0
Kim       NaN
Lee     140.0
jang      NaN
kang      NaN
Name: Total score, dtype: float64


In [260]:
data = {"mid" : [30, 32, 28, 20, 19], "hw" : [10, 9, 7, 8, 10], "fin" : [29, 27, 31, 18, 21],
       "gender" : ["M", "F", "M", "M", "F"]}
df = DataFrame(data)
print(data)
print("\n")
print(df)

{'mid': [30, 32, 28, 20, 19], 'hw': [10, 9, 7, 8, 10], 'fin': [29, 27, 31, 18, 21], 'gender': ['M', 'F', 'M', 'M', 'F']}


   mid  hw  fin gender
0   30  10   29      M
1   32   9   27      F
2   28   7   31      M
3   20   8   18      M
4   19  10   21      F


In [262]:
df = DataFrame(data, columns = ["gender", "hw", "att", "mid", "fin"])
print(df)

  gender  hw  att  mid  fin
0      M  10  NaN   30   29
1      F   9  NaN   32   27
2      M   7  NaN   28   31
3      M   8  NaN   20   18
4      F  10  NaN   19   21


In [271]:
arr = np.array([[10, 25, 32, 42], [85, 75, 96, 45], [68, 78, 94, 83]])
print(arr)
print("\n")
df = DataFrame(arr, columns=["V1","V2", "V3", "V4"], index=["A", "B", "C"])
print(df)

[[10 25 32 42]
 [85 75 96 45]
 [68 78 94 83]]


   V1  V2  V3  V4
A  10  25  32  42
B  85  75  96  45
C  68  78  94  83


In [273]:
data = {"mid" : [30, 32, 28, 20, 19], "hw" : [10, 9, 7, 8, 10], "fin" : [29, 27, 31, 18, 21],
       "gender" : ["M", "F", "M", "M", "F"]}
df = DataFrame(data, index=[2017103, 2018212, 2017204, 2019137, 2018217])
print(df)

mid  hw  fin gender
2017103   30  10   29      M
2018212   32   9   27      F
2017204   28   7   31      M
2019137   20   8   18      M
2018217   19  10   21      F

In [275]:
print(df.columns,"\n", df.index)

Index(['mid', 'hw', 'fin', 'gender'], dtype='object') 
 Int64Index([2017103, 2018212, 2017204, 2019137, 2018217], dtype='int64')


In [278]:
print(df.loc[2017204]) #행의 데이터를 가져온다
print("\n")
print(df.iloc[2])  #ilo은 줄 번호로 처리한다.

mid       28
hw         7
fin       31
gender     M
Name: 2017204, dtype: object


mid       28
hw         7
fin       31
gender     M
Name: 2017204, dtype: object


In [284]:
print(df.loc[[2017204,2017103]])
print("\n")
print(df.iloc[[2, 0, 3]]) #펜스인덱싱

         mid  hw  fin gender
2017204   28   7   31      M
2017103   30  10   29      M


         mid  hw  fin gender
2017204   28   7   31      M
2017103   30  10   29      M
2019137   20   8   18      M
