In [0]:
#comma가 없다는것은 리스트가 아니다.
import numpy as np
ls = [2,6,8,7,5,6]
x =  np.array([2,6,8,7,5,6])
print(ls[2],ls[:4],ls[1:4:2])
print(x[2], x[:4], x[1:4:2])

ls[2:5] = [6] #2번부터 5번전까지의 리스트를 [6]으로 변경
print(ls) #mutable data
#x[2:5] =6
print(x)

8 [2, 6, 8, 7] [6, 7]
8 [2 6 8 7] [6 7]
[2, 6, 6, 6]
[2 6 8 7 5 6]


In [0]:
x_sub1 = x[1:5]
x_sub2 = x[1:5].copy()

print(x, x_sub1, x_sub2)

x[2] = 100

print(x, x_sub1, x_sub2)



[2 6 8 7 5 6] [6 8 7 5] [6 8 7 5]
[  2   6 100   7   5   6] [  6 100   7   5] [6 8 7 5]


In [32]:
A = np.array([  [2,6,8,7], [25,31,78,96], [101,204,109,157]  ])
print(A)
print("\n")
print(A[2],"\n","\n", A[:2])
print("\n")
print(A[2][1], A[2,1])
print("\n")
print(A[:2, 1:3])

[[  2   6   8   7]
 [ 25  31  78  96]
 [101 204 109 157]]


[101 204 109 157] 
 
 [[ 2  6  8  7]
 [25 31 78 96]]


204 204


[[ 6  8]
 [31 78]]


In [46]:
arr3d = np.array([[[2,6,8,7], [25,31,78,96]],
                  [[102,297,304,487], [3,5,9,5]]])
print(arr3d)
print("\n")
print(arr3d[0][1][2],arr3d[0,1,2])
print("\n")
print(arr3d[0,1])

arr3d_sub1 = arr3d[0,1]
arr3d_sub2 = arr3d[0,1].copy()
print(arr3d_sub1,arr3d_sub2)
#arr3d_sub1[0,1,2] =  100
#print(arr3d_sub1,arr3d_sub2)


[[[  2   6   8   7]
  [ 25  31  78  96]]

 [[102 297 304 487]
  [  3   5   9   5]]]


78 78


[25 31 78 96]
[25 31 78 96] [25 31 78 96]


In [58]:
name = np.array(["남자", "여자", "남자", "남자", "남자", "여자"])
score = np.array([[10,20,30,40],[8,15,24,31],[5,11,20,25],
                [6,9,16,17],[10,17,21,27],[9,13,27,31]])
name_bool = name =="여자"

print(name,"\n","\n",score,"\n","\n",name_bool)

['남자' '여자' '남자' '남자' '남자' '여자'] 
 
 [[10 20 30 40]
 [ 8 15 24 31]
 [ 5 11 20 25]
 [ 6  9 16 17]
 [10 17 21 27]
 [ 9 13 27 31]] 
 
 [False  True False False False  True]


In [61]:
female = score[name_bool]
print(female)

print("\n")

male = score[~name_bool]
print(male)

[[ 8 15 24 31]
 [ 9 13 27 31]]


[[10 20 30 40]
 [ 5 11 20 25]
 [ 6  9 16 17]
 [10 17 21 27]]


In [73]:
cls = np.array(["1학년", "2학년","3학년","1학년", "2학년","3학년"])

score = np.array([[10,20,30,40],[8,15,24,31],[5,11,20,25],
                  [6,7,16,17],[10,17,21,27],[9,13,27,31]])

print(score[(cls=="1학년") | (cls == "2학년")])

[[10 20 30 40]
 [ 8 15 24 31]
 [ 6  7 16 17]
 [10 17 21 27]]


In [74]:
score[(cls=="1학년") | (cls == "2학년")] = 0
print(score)

[[ 0  0  0  0]
 [ 0  0  0  0]
 [ 5 11 20 25]
 [ 0  0  0  0]
 [ 0  0  0  0]
 [ 9 13 27 31]]


In [75]:
score[score >= 20] =100
print(score)

[[  0   0   0   0]
 [  0   0   0   0]
 [  5  11 100 100]
 [  0   0   0   0]
 [  0   0   0   0]
 [  9  13 100 100]]


In [80]:
arr = np.random.rand(7,4)
print(arr)

[[0.49328911 0.74625439 0.67486681 0.74266397]
 [0.04774902 0.77923024 0.66329729 0.66106296]
 [0.90797861 0.64235168 0.61224446 0.13496036]
 [0.16177257 0.5525705  0.59531411 0.9720748 ]
 [0.62750262 0.46313194 0.64182839 0.71749467]
 [0.10036059 0.96901286 0.71384014 0.07765201]
 [0.4957734  0.10159982 0.10943886 0.95906143]]


In [82]:
arr1 = arr[[6,3,5]] #6번행 3번행 5번행 차례대로 가져와라 이게 펜스 인덱싱
print(arr1)

[[0.4957734  0.10159982 0.10943886 0.95906143]
 [0.16177257 0.5525705  0.59531411 0.9720748 ]
 [0.10036059 0.96901286 0.71384014 0.07765201]]


In [83]:
arr2 = arr[[-1,-4,-2]] #맨 마지막 행 부터 0, -1, -2 순서
print(arr2)

[[0.4957734  0.10159982 0.10943886 0.95906143]
 [0.16177257 0.5525705  0.59531411 0.9720748 ]
 [0.10036059 0.96901286 0.71384014 0.07765201]]


In [84]:
arr3 = arr[[5,0,2],[1,0,2]] #5번,0번,2번행에서 (5번행에서 가로로 1번째 값, 0번행에서 가로로 0번째 값을 가져온다.
print(arr3)

[0.96901286 0.49328911 0.61224446]


In [88]:
arr4 = arr[[5,0,2]][:,[1,0,2]] #5,0,2행에서 1번원소,0번원소,2번원소를 차례대로 뽑아옴
arr5 = arr[np.ix_([5,0,2],[1,0,2])]

print(arr4)
print(arr5)

[[0.96901286 0.10036059 0.71384014]
 [0.74625439 0.49328911 0.67486681]
 [0.64235168 0.90797861 0.61224446]]
[[0.96901286 0.10036059 0.71384014]
 [0.74625439 0.49328911 0.67486681]
 [0.64235168 0.90797861 0.61224446]]


In [96]:
arr = np.arange(28).reshape(4,7)
print(arr)
print("\n")
arr1 = arr.T
arr2 = arr.transpose()
print(arr1)
print("\n")
print(arr2)

[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]]


[[ 0  7 14 21]
 [ 1  8 15 22]
 [ 2  9 16 23]
 [ 3 10 17 24]
 [ 4 11 18 25]
 [ 5 12 19 26]
 [ 6 13 20 27]]


[[ 0  7 14 21]
 [ 1  8 15 22]
 [ 2  9 16 23]
 [ 3 10 17 24]
 [ 4 11 18 25]
 [ 5 12 19 26]
 [ 6 13 20 27]]


In [101]:
arr = np.arange(24).reshape(2,4,3) #앞에서부터 인덱스가 0,1,2임
print(arr)
print("\n")
arr1 = arr.transpose(2,0,1) #위의 인덱스를 이용 인덱스 번호에 따라서 3,2,4가 들어감
print(arr1)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]


[[[ 0  3  6  9]
  [12 15 18 21]]

 [[ 1  4  7 10]
  [13 16 19 22]]

 [[ 2  5  8 11]
  [14 17 20 23]]]


NaN == null

In [121]:
x = np.array([2.5, 5.6, 8.1, 3.9, 5.7])
y = np.array([2, 6, -3, 4, -5])
A = np.array([x,y])

print(np.sqrt(x))
print("\n")
print(np.exp(x))
print("\n")
print(np.rint(np.exp(x))) #소수점 자르기
print("\n")
print(np.log(x))
print("\n")
print(np.abs(y))
print("\n")
print(np.sign(y))
print("\n")
r, q = np.modf(A) #실수부봐 소수부로 찢음
print(r)
print("\n")
print(q)

[1.58113883 2.36643191 2.84604989 1.97484177 2.38746728]


[  12.18249396  270.42640743 3294.46807528   49.40244911  298.86740097]


[  12.  270. 3294.   49.  299.]


[0.91629073 1.7227666  2.09186406 1.36097655 1.74046617]


[2 6 3 4 5]


[ 1  1 -1  1 -1]


[[ 0.5  0.6  0.1  0.9  0.7]
 [ 0.   0.  -0.   0.  -0. ]]


[[ 2.  5.  8.  3.  5.]
 [ 2.  6. -3.  4. -5.]]


In [140]:
A = (np.random.randn(12)*3+10).reshape(4,3)
B = np.arange(1,13).reshape(4,3)

print(A+B)
print("\n")
print(np.add(A,B))
print("\n")
print(np.subtract(A,B))
print("\n")
print(np.multiply(A,B))
print(np.divide(A,B))
print(np.floor_divide(A,B))

[[ 8.32988844  6.83341382 12.29920332]
 [16.5646985  18.38763865 17.96870066]
 [11.1691189  13.58126066 19.75628904]
 [21.58076365 20.33021912 22.64453224]]


[[ 8.32988844  6.83341382 12.29920332]
 [16.5646985  18.38763865 17.96870066]
 [11.1691189  13.58126066 19.75628904]
 [21.58076365 20.33021912 22.64453224]]


[[ 6.32988844  2.83341382  6.29920332]
 [ 8.5646985   8.38763865  5.96870066]
 [-2.8308811  -2.41873934  1.75628904]
 [ 1.58076365 -1.66978088 -1.35546776]]


[[  7.32988844   9.66682764  27.89760995]
 [ 50.258794    66.93819326  71.81220393]
 [ 29.18383227  44.65008529  96.80660133]
 [115.80763653 102.63241033 127.73438685]]
[[7.32988844 2.41670691 3.09973444]
 [3.14117462 2.67752773 1.99478344]
 [0.59558841 0.69765758 1.19514323]
 [1.15807637 0.84820174 0.88704435]]
[[7. 2. 3.]
 [3. 2. 1.]
 [0. 0. 1.]
 [1. 0. 0.]]
